### ISSUE TITLE
Problem with shareInstances option

### ISSUE THREAD

**Issue by tontof** [Level-2/Dice#86]
I've tried to update old code using v1 of Dice with v2 but I have an error with sharedInstances option.
My two objects are correctly created but the instance that was supposed to be shared are different.

I've tried using a small example from your website: https://r.je/dice.html#example3-7
But it does not work. The error is different, but I think the problem is linked. Here the A object is not created correctly

Here is the code
```PHP
<?php
include('../Dice/Dice.php');

class A {
    public $b, $c;
    public function __construct(B $b, C $c) { }
}

class B {
    public $d;
    public function __construct(D $d) {
        $this->d = $d;
    }
}

class C {
    public $d;
    public function __construct(D $d) {
        $this->d = $d;
    }
}

class D {}

$rule = [
    'shareInstances' => ['D']
];

$dice = new Dice\Dice();
$dice->addRule('A', $rule);

//Create an A object
$a = $dice->create('A');

var_dump($a); 
/*
  class A#20 (2) {
    public $b => NULL
    public $c => NULL
  }
*/
```
I'm using v2.0-PHP5.4-5.5 branch with PHP 5.5.9

BTW, on your website, there are few mistakes:
```PHP
$rule = [
    'shareInstances' = ['D']
];
```
should be
```PHP
$rule = [
    'shareInstances' => ['D']
];
```
And ```var_dumb``` is ```var_dump```

**Comment by tontof** [comment]
I forgot but phpunit is correct:
OK (90 tests, 147 assertions)

**Comment by TomBZombie** [comment]
Thanks for pointing this out, the example code is missing two lines in the A class constructor which should be:

```

    	$this->b = $b;
    	$this->c = $c;
```

I'll update the example code and fix the other typos you highlighted

**Comment by tontof** [comment]
Arf, I miss this error in your constructor. I thought that was an error linked to mine but it's not, I will try to figure out why my shareInstances does not work as I expected :-)

**Comment by tontof** [comment]
I'm sorry, but I don't understand why it does not work as I thought.
```PHP
<?php
include('../Dice/Dice.php');

interface BI {};
interface CI {};

class A {
    public $b, $c;
    public function __construct(BI $b, CI $c) {
        $this->b = $b;
        $this->c = $c;
    }
}

class B implements BI{
    public $d;
    public function __construct(D $d) {
        $this->d = $d;
    }
}

class C implements CI{
    public $d;
    public function __construct(D $d) {
        $this->d = $d;
    }
}

class D {}

$rule = [
    'instanceOf' => 'A',
    'constructParams' => [
        ['instance' => 'B'],
        ['instance' => 'C'],
    ],
    'shareInstances' => ['D']
];

$dice = new Dice\Dice();
$dice->addRule('A', $rule);

//Create an A object
$a = $dice->create('A');

var_dump($a);
/*
  class A#9 (2) {
  public $b =>
  class B#15 (1) {
    public $d =>
    class D#11 (0) {
    }
  }
  public $c =>
  class C#21 (1) {
    public $d =>
    class D#17 (0) {
    }
  }
}
*/
```
Should D not be shared ??
In order to work, I need to modify rules:
```PHP
$rule = [
    'instanceOf' => 'A',
    'shareInstances' => ['D']
];

$dice = new Dice\Dice();
$dice->addRule('A', $rule);
$dice->addRule('BI', ['instanceOf' => 'B']);
$dice->addRule('CI', ['instanceOf' => 'C']);
```
That way it works great!

**Comment by TomBZombie** [comment]
Thanks. Yes, there is an issue here. I've fixed it. shareInstances weren't correctly being supplied to instances created via constructParams.

**Comment by tontof** [comment]
Thanks a lot!!!
(You forgot to push your modification to ```v2.0-PHP5.4-5.5```... I still don't have PHP 5.6 ^^)
Actually I don't really know which branch I should use for PHP5.5 :-)

I have a last question. Suppose you add this to code above before ```A``` creation: 
```PHP
$dice->addRule('B', ['constructParams' => ['instance' => 'D']]);
```
Now again,  with ```$a = $dice->create('A');```, ```D``` is not shared anymore. I don't know what to think about that. Do you think it's a bug or normal ? :-)

Thanks again for your wonderful codeS

**Comment by TomBZombie** [comment]
Hmm.. that's a good question. It should probably be shared, I certainly can't think of a situation where you would want to force a new instance there. I'll see if there's an easy way to resolve that

Thanks :) Glad you're finding it useful!

**Comment by TomBZombie** [comment]
The problem here is the syntax.

```php
$dice->addRule('B', ['constructParams' => ['instance' => 'D']]);
```

should really be:

```php
$dice->addRule('B', ['constructParams' => [
      ['instance' => 'D']
    ]
]);
```

Because constructParams should be an array of instances and ` ['instance' => 'D']` resolves to a single instance.

**Comment by tontof** [comment]
My bad, I forgot square brackets in my example code when I've rewrited it.

With your last commit it works like a charm !

**Comment by tontof** [comment]
Oups, here is an other example where I have a strange problem
```php
class A {
    public function __construct($a = '', D $d) {
        var_dump($d);
        var_dump($a);
    }
}

class B {
    public function __construct(D $d) {}
}

class C {
    public function __construct(A $a, B $b) {}
}

$dice = new Dice\Dice;
$dice->create('C');
/*
class D#14 (0) {
}
string(0) ""
*/
```
Everything seems to be OK but if I add shareInstances:
```php
class A {
    public function __construct($a = '', D $d) {
        var_dump($d);
        var_dump($a);
    }
}

class B {
    public function __construct(D $d) {}
}

class C {
    public function __construct(A $a, B $b) {}
}

$dice = new Dice\Dice;
$dice->addRule('C', ['shareInstances' => ['D']]);
$dice->create('C');
/*
class D#14 (0) {
}
class D#9 (0) {
}
*/
```

```$a``` is now of class D

**Comment by TomBZombie** [comment]
Dice takes a best match approach so it will use the first available value that can fit the argument. As it has to create the `D` instance, it will pass it in to the first available slot.

Having it work any other way would cause other issues when trying to pass objects to non-hinted parameters. In this case, I think the only way to resolve the issue is to pass a valid value for A's `constructParams`

Keep in mind what

`new A(new D)` will do. You'll need to provide the relevant first constructor parameter for A for this to work.

**Comment by TomBZombie** [comment]
This resolves the issue:

```php
$dice->addRule('A', ['constructParams' => [
		'str'
]]);

```

**Comment by tontof** [comment]
Well, I guess I see the problem for that example where modifying the constructor as
```php
public function __construct(D $d, $a = '')
```
also fix the problem.

However, on my real life example, it seems to be quite different and I'm not sure if it will work using ```constructParams```.
I will try and let you know

**Comment by garrettw** [comment]
As a rule of thumb, all optional parameters should be at the end of the parameter list.

**Comment by TomBZombie** [comment]
Not just a rule of thumb, it's impossible to have a required second argument and an optional first argument.

```
new A(); //Fails as D is required
new A('foo'); //Fails as D is required
new A('foo', $d); //Works.. but you have to have specified argument 1 to specify argument 2
```

**Comment by tontof** [comment]
Yep, that's obvious, when I've tried to simplify my real world example, I've changed stuff and it introduces this error in constructor even if it was not really the purpose of this problem.

Here is an example where the order in constructor does not and where I also provide constructParams
```PHP
class A {
    public function __construct(C $vm, $t = '') {
        var_dump($vm);
        var_dump($t);
    }
}

class B {
    public function __construct(A $v) {
    }
}

class C {}

$dice->addRule('A', [
    'constructParams' => [
        ['instance' => 'C'],
        'toto',
    ]    
]);
    
$dice->addRule('B', [
    'constructParams' => [
        ['instance' => 'A']
    ],
    'shareInstances' => ['C']
]);

$dice->create('B');
/*
class C#8 (0) {
}
class C#10 (0) {
}
*/
```
without ```shareInstances``` it works.

I've tried using 53ca10c2dda and it works. I guess it's linked to the last modification about shareInstances...

**Comment by tontof** [comment]
I don't know if it can help for finding the problem, but if you add a parameter to B for testing sharing property
```PHP
class A {
    public function __construct(C $c, $d = '') {
        var_dump($c);
        var_dump($d);
    }
}

class B {
    public function __construct(A $a, A $b) {
    }
}

class C {}

$dice->addRule('A', [
    'constructParams' => [
        ['instance' => 'C'],
        'toto',
    ]    
]);

$dice->addRule('B', [
    'constructParams' => [
        ['instance' => 'A']
    ],
    'shareInstances' => ['C']
]);

$dice->create('B');
/*
class C#9 (0) {
}
class C#11 (0) {
}
class C#11 (0) {
}
string(4) "toto"
*/
```
using 53ca10c2dda, no problem
```PHP
/*
class C#11 (0) {
}
string(4) "toto"
class C#11 (0) {
}
string(4) "toto"
*/
```

**Comment by tontof** [comment]
Arf, it works without constructParams information for B
```PHP
class A {
    public function __construct(C $c, $d = '') {
        var_dump($c);
        var_dump($d);
    }
}

class B {
    public function __construct(A $a, A $b) {
    }
}

class C {}

$dice->addRule('A', [
    'constructParams' => [
        ['instance' => 'C'],
        'toto',
    ]    
]);

$dice->addRule('B', [
    'shareInstances' => ['C']
]);

$dice->create('B');
/*
class C#11 (0) {
}
string(4) "toto"
class C#11 (0) {
}
string(4) "toto"
 */
```

**Comment by TomBZombie** [comment]
I don't think there will be a fix for every use-case here. Either constructParams or shareInstances must have precedence. In some of your examples it should be one and in the others it needs to be the other... I'll take a look but I don't think there is an easy fix for this

**Comment by tontof** [comment]
No problem. I'm still a little bit confused about that and I do not catch yet when it will work or not as I expect :-)

I guess that using constructParams or shareInstances may lead to some problems as above. I've tried to simplify again and with this code:
```PHP
class A {
    public function __construct(C $c, $d = '') {
        var_dump($c);
        var_dump($d);
    }
}

class B {
    public function __construct(A $a, A $b) { }
}

class C {}

$dice->addRule('A', [
    'constructParams' => [
        ['instance' => 'C'],
        'toto',
    ],
]);

$dice->create('B');
/*
class C#14 (0) {
}
string(4) "toto"
class C#14 (0) {
}
string(4) "toto"
*/
```
I don't understand why ```C``` is shared. I've checked and ```A $a``` and ```A $b``` are different in ```B```
Even if I add ```$dice->addRule('C', ['shared' => false]);```, I've got the same result. Is it linked to the use of 'instance' option ?

**Comment by TomBZombie** [comment]
I'm not seeing this at all Using the exact code above, I'm getting:

```php
class C#16 (0) {
}
string(4) "toto"
class C#17 (0) {
}
string(4) "toto"


```

**Comment by TomBZombie** [comment]
It seems to be an issue with

```
return $class->newInstanceArgs($params($args, $share)); 
```

How is that different to the PHP5.6 version:

```
return new $class->name(...$params($args, $share)); 
```

Very odd...

**Comment by TomBZombie** [comment]
Ok, changing it to 
```
$params = clone $params;
return $class->newInstanceArgs($params($args, $share)); 
```

Fixes it... I have no idea why as the same logic is run when the function is called... not an ideal solution as I don't understand what the problem actually is.

**Comment by TomBZombie** [comment]
I've created a completely minimal version of Dice and it still presents the same issue (with or without any rules set)

```php

<?php

class Dice {
	private $cache = [];

	public function create($name, array $args = [], array $share = []) {
		if (empty($this->cache[$name])) $this->cache[$name] = $this->getClosure($name);
		return $this->cache[$name]($args, $share);
	}

	private function getClosure($name) {
		$class = new \ReflectionClass($name);
		$constructor = $class->getConstructor();
		$params = $constructor ? $this->getParams($constructor) : null;

		 if ($params) $closure = function (array $args, array $share) use ($class, $params) { 
		//	uncomment this line and it works.... why?
		//	$params = clone $params;
			$p = $params($args, $share);
			return new $class->name(...$p); 
		};
		else $closure = function () use ($class) { return new $class->name;	};

		return  $closure;
	}


	private function getParams(\ReflectionMethod $method) {
		$paramInfo = [];
		foreach ($method->getParameters() as $param) {
			$class = $param->getClass() ? $param->getClass()->name : null;
			$paramInfo[] = [$class, $param];
		}
		return function (array $args, array $share = []) use ($paramInfo) {			
			$parameters = [];

			foreach ($paramInfo as $p) {
				list($class, $param) = $p;

				if ($class) $parameters[] = $this->create($class, [], $share);
			}
			return $parameters;
		};
	}
}





class A {
    public function __construct(C $c, $d = '') {
        var_dump($c);
        var_dump($d);
    }
}

class B {
    public function __construct(A $a, A $b) { }
}

class C {}


$dice = new Dice();

$dice->create('B');


```

**Comment by TomBZombie** [comment]
Ok... I see the issue and it''s not really an issue. It's a problem with garbage collection. Try this:


```php
var_dump(new C);
var_dump(new C);
```

"same" instance numerically..

Now this:

```php

$c1 = new C;
$c2 = new C;


var_dump($c1);
var_dump($c2);
```

Different instances!

That's because the object is never stored anywhere in the first example so the garbage collector removes it. The same thing happens here:


```php
 public function __construct(C $c, $d = '') {
        var_dump($c);
        var_dump($d);
    }
```

Because the `$c` instance is no longer referenced anywhere in the code, it's removed by the garbage collector. The next time a C instance is created it gets the same ID.

Changing the code to:

```php
class A {
	private $c;

    public function __construct(C $c, $d = '') {
    	$this->c = $c;
        var_dump($c);
        var_dump($d);
    }
}

class B {
    public function __construct(A $a, A $b) {
    	
    }
}

class C {}

require_once 'Dice.php';

$dice = new \Dice\Dice;


$dice->create('B');

```

Works.

**Comment by tontof** [comment]
I've replaced your code ```...``` to work with PHP 5.5 using
```PHP
return $class->newInstanceArgs($params($args, $share));
```
I don't know if it's equivalent but in both case (commenting or not the line), I have the same behavior.

**Comment by TomBZombie** [comment]
see my comment above... it's to do with the garbage collector in PHP, not a bug :)

**Comment by tontof** [comment]
Oups, sorry about that... Well at least, there is an explanation, well done!
I comment just before I see your comment. I guess you can close this issue now (definitely?) :-)

**Comment by TomBZombie** [comment]
There is likely still a scenario where having both `constructParams` and `shareInstances` will have unpredictable results, however as one of them will always need precedence there may not be an easy fix. 

I'll close this for now, but if you find one of these post it and I'll see if there's a way to work around it.
